apiVersion: v1
kind: Pod
metadata:
  name: postgres-grabngo
  labels:
    app: postgres-grabngo
spec:
  containers:
  - name: postgres
    image: postgres:latest
    env:
    - name: POSTGRES_PASSWORD
      value: postgres
    ports:
    - containerPort: 5432