apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grabngo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grabngo-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
