apiVersion: apps/v1
kind: Deployment
metadata:
  name: grabngo-deployment
  labels:
    app: grabngo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grabngo
  template:
    metadata:
      labels:
        app: grabngo
    spec:
      containers:
        - name: grabngo
          image: ''
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: grabngo-secrets  
                  key: databaseUrl  